name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: neuraleduseg-service

jobs:

  build:
    name: Build, test and publish Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.run_number }} .
    - name: Run pytest in Docker
      run: docker run --entrypoint=pytest $IMAGE_NAME

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Publish Docker image
      run: docker push $IMAGE_NAME
